---
- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0644
  notify: restart_k3s

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Create directory .kube on root
  file:
    path: /root/.kube
    state: directory
    mode: "u=rwx,g=rx,o="

- name: Copy original config file to user home directory for backup
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/ansible
    remote_src: true
    mode: preserve
  notify: config_changed

- name: Force all notified handlers to run at this point
  meta: flush_handlers

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link
